name: docker

on:
  release:
    types: [published]


jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            crapware/sbcl-ocicl:latest
            crapware/sbcl-ocicl:${{ github.ref_name }}
